
spring:
    datasource:
        url : "@db.url@"
        username : "@db.user@"
        password : @db.pass@

        
mybatis:
    type-aliases-package : com.bamdule.example.model.*
    mapper-locations : mapper/xml/*.xml 
    
logback:
    logging.path : "@logging.path@"
    logging.level : "@logging.level@"
    